#################################### common config : ####################################
spring:
  cloud:
    nacos:
      server-addr: http://49.233.129.28:8848
  application:
    name: nacos_service1
server:
  port: 18001

