spring:
  application:
    name: auth-server
  redis:
    database: 0
    host:
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
    timeout: 100ms

server:
  port: 8000
management:
  endpoint:
    health:
      enabled: true
