spring:
  application:
    name: auth-server
  redis:
    database: 0
    host: 49.233.129.28
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
    timeout: 100ms

server:
  port: 8000
management:
  endpoint:
    health:
      enabled: true

##开启日志DEBUG级别，便于查看调试信息
logging.level.org.springframework.security: DEBUG
